pipeline {
  agent{
       docker{
         image 'maven:3.6.1-jdk-8-slim'
         args '-v $HOME/.m2:/root/.m2'
       }
    }

  stages{
      stage(build){
          steps{
              echo 'Build'
              dir('worker'){
                  sh 'mvn compile'
              }
          }
      }
      stage(test){
          steps{
              echo 'Test'
              dir('worker'){
                sh 'mvn clean test'
              }

          }
      }
      stage(package){
          when {
              branch 'master'
          }
          steps{
              echo 'Package'
              dir('worker'){
                sh 'mvn package -DskipTests'
                }
          }
      }
  }

  post{
    always{
        echo 'This pipeline is completed..'
    }
  }
}